apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
images:
  - name: ghcr.io/ziin-ai/signal-agent-content
    newTag: ab90eac038b7a13d0cdee4638476204b6063d6ce
