apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
images:
  - name: ghcr.io/ziin-ai/signal-agent-content
    newTag: 98c9b49f2026f2f33c247b58b2daabb9fd96ae75
