apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
images:
  - name: ghcr.io/ziin-ai/signal-agent-content
    newTag: bce1d4e4bb4715010c54f8b5ef3dfe1d778d94cc
