apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-agent
  namespace: signal-agent
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: web
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 1Gi
